data=LifeCycleSavings
data
sr=data$sr
pop15=data$pop15
pop75=data$pop75
dpi=data$dpi
ddpi=data$ddpi
y=sr/dpi
h=hist(y,xlab="Savings Ratio",main="Hisogram of Savings Ratio")
skewness(y)
kurtosis(y)
hbreaks=h$breaks
hbreaks
lcb=hbreaks[1:length(hbreaks)-1]
ucb=hbreaks[2:length(hbreaks)]
lcb
ucb
hcounts=h$counts
hcounts
y1=log(y)
m=mean(y1)
sd=sd(y1)
p=round(plnorm(ucb,m,sd)-plnorm(lcb,m,sd),4)
p
N=length(y1)
N
ef=N*p
ef
d=data.frame(lcb,ucb,hcounts,p,ef)
d
qqnorm(y1)
pairs(data)
cor.test(pop15,pop75,"two.sided","kendall")
cor.test(pop75,dpi,"two.sided","kendall")
cor.test(pop15,ddpi,"two.sided","kendall")
cor.test(pop75,ddpi,"two.sided","kendall")
cor.test(pop15,dpi,"two.sided","kendall")
f=lm(y~pop15+pop75+ddpi)
f
summary(f)
pred=predict(f,pop15=30,pop75=3,ddpi=4)
pred
f1=lm(y~pop15+ddpi)
f1
summary(f1)
f2=lm(y~pop75+ddpi)
f2
summary(f2)
cor(pop75,ddpi)
