data(airquality)
names(airquality)
plot(Ozone~Solar.R,data=airquality)
mean.Ozone=mean(airquality$Ozone,na.rm=T)
mean.Ozone
abline(h=mean.Ozone)
model1=lm(Ozone~Solar.R,data=airquality)
model1
abline(model1,col="maroon")
plot(model1)

summary(model1)
plot(Ozone~Wind,data=airquality)
coplot(Ozone~Solar.R|Wind,data=airquality)
model2=lm(Ozone~Solar.R*Wind,data=airquality)
model2
summary(model2)
plot(model2)
summary(airquality$Solar.R)
summary(airquality$Wind)
Solar1=185.9
Solar2=100
Solar3=300
p1=predict(model2,data.frame(Solar.R=Solar1,Wind=1:20))
p2=predict(model2,data.frame(Solar.R=Solar2,Wind=1:20))
p3=predict(model3,data.frame(Solar.R=Solar3,Wind=1:20))
plot(Ozone~Wind,airquality)
lines(1:20,p1)
lines(1:20,p2)
lines(1:20,p3)
